### ISSUE TITLE
For @Rexxt

### ISSUE THREAD

**Issue by locness3** [csourcesc/csourcesc.github.io#1]
@Rexxt, I know you will see this, because you're watching the repo.
On Prose, when you do a blog post, always click "Unpublished" in the editor, and add "layout: post" in the metadata (this ![Metadata button in Prose](https://screenshotscdn.firefoxusercontent.com/images/3f1125da-c6d1-4ea1-9820-41ad6959ed89.png) button) before saving so it displays correctly.

**Comment by Rexxt** [comment]
ok
