### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ghost** [csourcesc/csourcesc.github.io#12]
It would be nice to create a dark mode for the blog.

**Comment by moeenio** [comment]
Yeah, although that's not current focus :) But you're working on one aren't you?

**Comment by ghost** [comment]
No. (sry)

**Comment by moeenio** [comment]
Oh. that's fine :)

**Comment by moeenio** [comment]
@delnyn Please do not close, the request is still valid and still haven't been implemented yet.

**Comment by ghost** [comment]
okay

**Comment by ghost** [comment]
huh?
