### ISSUE TITLE
Use CSS variables instead of SASS variables

### ISSUE THREAD

**Issue by moeenio** [csourcesc/csourcesc.github.io#15]
Would allow for #12 

While I'm at it, I should rename them to follow [this Figma](https://www.figma.com/file/pKHaVKFcPDLDOIQIaOaK6L/Colors-and-Typography?node-id=3%3A2).

**Comment by ghost** [comment]
thanks

**Comment by moeenio** [comment]
🤔

**Comment by ghost** [comment]
I asked for the #12, so you are making this for me, kinda.

**Comment by moeenio** [comment]
While I'm at it, I should rename them to follow [this Figma](https://www.figma.com/file/pKHaVKFcPDLDOIQIaOaK6L/Colors-and-Typography?node-id=3%3A2).

**Comment by ghost** [comment]
Okay

**Comment by ghost** [comment]
Could you assign it to me please, @locness3  ?
I will be able to check this out tomorrow.
