### ISSUE TITLE
Change Grayples' colors

### ISSUE THREAD

**Issue by ghost** [csourcesc/csourcesc.github.io#19]
"But wider problem, dark grayple and grayple don't have enough contrast between them IMO."

_Originally posted by @locness3 in https://github.com/csourcesc/csourcesc.github.io/pull/18#issuecomment-648057662_

**Comment by moeenio** [comment]
yup

**Comment by ghost** [comment]
So what are we doing?

**Comment by moeenio** [comment]
idk

**Comment by ghost** [comment]
Great!

**Comment by ghost** [comment]
So here is my proposal  
![image](https://user-images.githubusercontent.com/45879791/94050966-3cea3780-fdd7-11ea-96b3-38bc8b005c2f.png)  
- `#2F2640` for `darkGrayple`  
- `#77609F` for `grayple`  
- `#C8BFD9` for `lightGrayple`  
  
I also sugggest to rename those variables to `grayple1`, `grayple2` and `grayple3`.

**Comment by moeenio** [comment]
And so darkGrayple would do main text?

**Comment by moeenio** [comment]
![Screen Shot 2020-09-24 at 06 59 26](https://user-images.githubusercontent.com/37651007/94102913-81a3bc00-fe33-11ea-9096-6a5171849eaf.png)
The light grayple's maybe too light

**Comment by ghost** [comment]
Hm... I think we should make new guidelines. I could do that. I just need you to let me edit the Figma, I'll do it on a new page.

**Comment by ghost** [comment]
Remade the color palette, we can close this!
