### ISSUE TITLE
Remake design guidelines

### ISSUE THREAD

**Issue by ghost** [csourcesc/csourcesc.github.io#20]
Hm... I think we should make new guidelines. I could do that. I just need you to let me edit the Figma, I'll do it on a new page.

_Originally posted by @delnyn in https://github.com/csourcesc/csourcesc.github.io/issues/19#issuecomment-698159752_

**Comment by moeenio** [comment]
Just invited you to the team

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
@locness3 Well I'm giving up on the guidelines thing; but I created a new color palette (it's in the Figma file), and I guess we should use it.
