### ISSUE TITLE
Make a new README

### ISSUE THREAD

**Issue by ghost** [csourcesc/csourcesc.github.io#22]
- [x] Add context, change the image.
- [x] How to install & run

**Comment by ghost** [comment]
Why backlog? I'm working on it right now

**Comment by moeenio** [comment]
progress?

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
hold on

**Comment by ghost** [comment]
@locness3 I need to know how to install it

**Comment by moeenio** [comment]
clone the repo [with the `--recursive` option](https://stackoverflow.com/a/4438292/10074924), then do [this](https://jekyllrb.com/docs/) within it, skipping step 3 obviously and doing `bundle install` before step 5

**Comment by ghost** [comment]
ok thanks, I'll do that later

**Comment by ghost** [comment]
Done! PR-ing it
