### ISSUE TITLE
support Dillo

### ISSUE THREAD

**Issue by moeenio** [csourcesc/csourcesc.github.io#27]
Would be nice to support the Dillo browser, i'm not even kidding

**Comment by ghost** [comment]
oh come on

**Comment by moeenio** [comment]
it already works 99%

**Comment by ghost** [comment]
okay nice

**Comment by moeenio** [comment]
When major web browsers are heavy and feature-bloated, Dillo is simple and lightweight - which I totally am for, and I'm trying to make CatSource as simple and lightweight as possible too. Sadly, without any proper support from websites Dillo is useless - that's probably why it's not really under active development
