### ISSUE TITLE
Improve the privacy banner

### ISSUE THREAD

**Issue by moeenio** [csourcesc/csourcesc.github.io#29]
It recently came to me that our privacy information banner is - unintentionnally - designed for the user to click past it and not read it - what most websites do to pretend they have consent from their users. The opt-out should have as much emphasis as the close button, and the text could also be rephrased, mostly to emphasize that we manage our analytics ourselves.

**Comment by ghost** [comment]
yeah I'll change that

**Comment by delnyn** [comment]
can we consider this as done?
