### ISSUE TITLE
Category and tags link all 404

### ISSUE THREAD

**Issue by moeenio** [csourcesc/csourcesc.github.io#36]
even though they worked locally

**Comment by moeenio** [comment]
basically github doesn't support the jekyll-archives gem

**Comment by moeenio** [comment]
might want to use this https://www.drinkingcaffeine.com/deploying-jekyll-to-github-pages-without-using-githubs-jekyll/

**Comment by ghost** [comment]
OK, you'll have to deal with it since I don't know how to

**Comment by moeenio** [comment]
[or this better](https://jekyllrb.com/docs/continuous-integration/github-actions/)
